"""Load, inspect, and visualize synthetic scene layouts generated by iARCS.

The generation script (scripts/generate.py) produces a results.pkl file
containing a ThreedFrontResults object. This script shows how to load the
generated layouts and optionally render 2D top-down views.

Each layout is a dict with keys:
    "class_labels"  : (N, C) one-hot class labels
    "translations"  : (N, 3) object center positions (x, y, z)
    "sizes"         : (N, 3) object half-extents (hx, hy, hz)
    "angles"        : (N, 1) rotation angle in radians

Usage:
    python scripts/using_synthetic_data.py --results path/to/results.pkl
    python scripts/using_synthetic_data.py --results path/to/results.pkl --plot --out views.png

If no --results is given, a small dummy file is created for demonstration.
"""
import argparse
import os
import pickle
import numpy as np


BEDROOM_LABELS = [
    "armchair", "bookshelf", "cabinet", "ceiling_lamp", "chair",
    "children_cabinet", "coffee_table", "desk", "double_bed",
    "dressing_chair", "dressing_table", "kids_bed", "nightstand",
    "pendant_lamp", "shelf", "single_bed", "sofa", "stool", "table",
    "tv_stand", "wardrobe",
]


def create_dummy_results(path):
    """Create a minimal dummy results file for demonstration."""
    num_scenes = 5
    layouts = []
    for i in range(num_scenes):
        n_objects = np.random.randint(4, 10)
        n_classes = len(BEDROOM_LABELS)
        class_labels = np.zeros((n_objects, n_classes + 1), dtype=np.float32)
        for j in range(n_objects):
            class_labels[j, np.random.randint(0, n_classes)] = 1.0
        layout = {
            "class_labels": class_labels,
            "translations": np.random.uniform(-3, 3, (n_objects, 3)).astype(np.float32),
            "sizes": np.random.uniform(0.1, 1.5, (n_objects, 3)).astype(np.float32),
            "angles": np.random.uniform(-np.pi, np.pi, (n_objects, 1)).astype(np.float32),
        }
        layouts.append(layout)
    data = {"scene_indices": list(range(num_scenes)), "layouts": layouts}
    os.makedirs(os.path.dirname(path) or ".", exist_ok=True)
    with open(path, "wb") as f:
        pickle.dump(data, f)
    print(f"Created dummy results with {num_scenes} scenes at {path}")
    return data


def load_results(path):
    """Load generated results from a pkl file.

    Handles both the ThreedFrontResults object format (from generate.py)
    and the simple dict format (from this demo).
    """
    with open(path, "rb") as f:
        data = pickle.load(f)

    if isinstance(data, dict) and "layouts" in data:
        return data["scene_indices"], data["layouts"]

    if hasattr(data, "_scene_indices") and hasattr(data, "_predicted_layouts"):
        return data._scene_indices, data._predicted_layouts

    raise ValueError(f"Unknown results format: {type(data)}")


def print_scene_summary(idx, layout):
    """Print a human-readable summary of one scene layout."""
    class_labels = layout["class_labels"]
    translations = layout["translations"]
    sizes = layout["sizes"]
    angles = layout["angles"]
    n_objects = class_labels.shape[0]

    print(f"\n  Scene {idx}: {n_objects} objects")
    print(f"  {'Object':<20s} {'Position (x,y,z)':<30s} {'Size (hx,hy,hz)':<30s} {'Angle':>8s}")
    print(f"  {'-'*90}")

    for j in range(n_objects):
        cls_idx = int(np.argmax(class_labels[j]))
        name = BEDROOM_LABELS[cls_idx] if cls_idx < len(BEDROOM_LABELS) else "empty"
        pos = translations[j]
        sz = sizes[j]
        ang = float(angles[j].item())
        print(f"  {name:<20s} ({pos[0]:6.2f}, {pos[1]:6.2f}, {pos[2]:6.2f})    "
              f"({sz[0]:5.2f}, {sz[1]:5.2f}, {sz[2]:5.2f})    {ang:8.3f}")


def plot_scene_topdown(ax, layout, title=""):
    """Draw a 2D top-down bounding box view of a scene on a matplotlib axis."""
    import matplotlib.patches as patches

    colors = [
        "#e6194b", "#3cb44b", "#ffe119", "#4363d8", "#f58231",
        "#911eb4", "#42d4f4", "#f032e6", "#bfef45", "#fabed4",
        "#469990", "#dcbeff", "#9A6324", "#fffac8", "#800000",
        "#aaffc3", "#808000", "#ffd8b1", "#000075", "#a9a9a9",
        "#000000",
    ]

    class_labels = layout["class_labels"]
    translations = layout["translations"]
    sizes = layout["sizes"]
    angles = layout["angles"]

    for j in range(class_labels.shape[0]):
        cls_idx = int(np.argmax(class_labels[j]))
        name = BEDROOM_LABELS[cls_idx] if cls_idx < len(BEDROOM_LABELS) else "empty"
        if name == "empty":
            continue

        cx, _, cz = translations[j]
        hx, _, hz = sizes[j]
        ang = float(angles[j].item())

        corners = np.array([[-hx, -hz], [hx, -hz], [hx, hz], [-hx, hz]])
        cos_a, sin_a = np.cos(ang), np.sin(ang)
        rot = np.array([[cos_a, -sin_a], [sin_a, cos_a]])
        corners = corners @ rot.T + np.array([cx, cz])

        poly = patches.Polygon(corners, closed=True,
                               facecolor=colors[cls_idx % len(colors)],
                               edgecolor="black", linewidth=0.5, alpha=0.7)
        ax.add_patch(poly)
        ax.text(cx, cz, name, fontsize=4, ha="center", va="center")

    ax.set_xlim(-4, 4)
    ax.set_ylim(-4, 4)
    ax.set_aspect("equal")
    ax.set_title(title, fontsize=7)
    ax.tick_params(labelsize=5)


def plot_scenes(layouts, scene_indices, out_path, max_scenes=16):
    """Render a grid of 2D top-down scene views."""
    import matplotlib
    matplotlib.use("Agg")
    import matplotlib.pyplot as plt

    n = min(len(layouts), max_scenes)
    cols = min(n, 4)
    rows = (n + cols - 1) // cols
    fig, axes = plt.subplots(rows, cols, figsize=(3 * cols, 3 * rows))
    if n == 1:
        axes = np.array([axes])
    axes = axes.flatten()

    for i in range(n):
        plot_scene_topdown(axes[i], layouts[i], title=f"Scene {scene_indices[i]}")
    for i in range(n, len(axes)):
        axes[i].axis("off")

    plt.tight_layout()
    plt.savefig(out_path, dpi=200)
    plt.close()
    print(f"Saved {n} scene views to {out_path}")


def main():
    parser = argparse.ArgumentParser(description="Load and inspect iARCS-generated scenes")
    parser.add_argument("--results", default=None, help="Path to results.pkl")
    parser.add_argument("--max_scenes", type=int, default=3, help="Max scenes to display/plot")
    parser.add_argument("--plot", action="store_true", help="Generate 2D top-down views")
    parser.add_argument("--out", default="scene_views.png", help="Output image path (with --plot)")
    args = parser.parse_args()

    if args.results is None:
        dummy_path = os.path.join("data", "dummy_results.pkl")
        print("No --results provided. Creating dummy data for demonstration.\n")
        create_dummy_results(dummy_path)
        args.results = dummy_path

    scene_indices, layouts = load_results(args.results)
    print(f"Loaded {len(layouts)} scenes from {args.results}")

    for i, (scene_idx, layout) in enumerate(zip(scene_indices, layouts)):
        if i >= args.max_scenes:
            print(f"\n  ... and {len(layouts) - args.max_scenes} more scenes.")
            break
        print_scene_summary(scene_idx, layout)

    if args.plot:
        plot_scenes(layouts, scene_indices, args.out, args.max_scenes)

    print(f"\nFor full 3D rendering, see: https://github.com/MIT-SPARK/ThreedFront")


if __name__ == "__main__":
    main()
